import { z } from "zod";

export const contractStyleSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  version: z.string(),
  icon: z.string(),
  features: z.array(z.string()),
  entrypoints: z.object({
    mint: z.string(),
    transfer: z.string(),
    updateOperators: z.string().optional(),
    setRoyalties: z.string().optional(),
    addMinter: z.string().optional(),
    removeMinter: z.string().optional(),
    setPrice: z.string().optional(),
    clearPrice: z.string().optional(),
    buy: z.string().optional(),
    makeOffer: z.string().optional(),
    acceptOffer: z.string().optional(),
    rejectOffer: z.string().optional(),
    cancelOffer: z.string().optional(),
    withdraw: z.string().optional(),
    blacklistAddress: z.string().optional(),
    unblacklistAddress: z.string().optional(),
    setMaxBuyQty: z.string().optional(),
    setMinOfferPercentOfList: z.string().optional(),
    sweepExpiredOffer: z.string().optional(),
    createToken: z.string().optional(),
    mintEditions: z.string().optional(),
    setMintPrice: z.string().optional(),
    setMintEnd: z.string().optional(),
    setMintPausedForever: z.string().optional(),
    setMintingPaused: z.string().optional(),
    adminCancelExpiredOffer: z.string().optional(),
  }),
  recommended: z.boolean().optional(),
});

export type ContractStyle = z.infer<typeof contractStyleSchema>;

export const CONTRACT_STYLES: ContractStyle[] = [
  {
    id: "fa2-basic",
    name: "FA2 Basic",
    description: "Standard FA2 NFT contract with single admin. Perfect for simple collections with straightforward minting.",
    version: "1.0.0",
    icon: "Layers",
    features: ["FA2 compliant", "Single admin", "Batch transfer", "On-chain metadata"],
    entrypoints: {
      mint: "mint",
      transfer: "transfer",
      updateOperators: "update_operators",
    },
  },
  {
    id: "fa2-royalties",
    name: "FA2 + Royalties",
    description: "FA2 with built-in royalty distribution. Automatically splits secondary sales between creator and platform.",
    version: "1.0.0",
    icon: "Gem",
    features: ["FA2 compliant", "On-chain royalties", "EIP-2981 compatible", "Configurable split"],
    entrypoints: {
      mint: "mint",
      transfer: "transfer",
      updateOperators: "update_operators",
      setRoyalties: "set_royalties",
    },
  },
  {
    id: "fa2-multiminter",
    name: "FA2 Multi-Minter",
    description: "Collaborative minting with allowlist. Add multiple wallet addresses as authorized minters for your collection.",
    version: "1.0.0",
    icon: "Users",
    features: ["FA2 compliant", "Multi-admin", "Minter allowlist", "Role management"],
    entrypoints: {
      mint: "mint",
      transfer: "transfer",
      updateOperators: "update_operators",
      addMinter: "add_minter",
      removeMinter: "remove_minter",
    },
  },
  {
    id: "fa2-full",
    name: "FA2 Complete",
    description: "Full-featured contract with royalties, multi-minter support, and advanced metadata. The ultimate collection contract.",
    version: "1.0.0",
    icon: "Crown",
    features: ["FA2 compliant", "Royalties", "Multi-minter", "Advanced metadata", "Pausable"],
    entrypoints: {
      mint: "mint",
      transfer: "transfer",
      updateOperators: "update_operators",
      setRoyalties: "set_royalties",
      addMinter: "add_minter",
      removeMinter: "remove_minter",
    },
  },
  {
    id: "bowers-marketplace",
    name: "Bowers Marketplace",
    description: "Market-independent FA2 with built-in listings, partial-fill offers, pull payments, per-owner blacklists, and royalty distribution. The default Bowers contract.",
    version: "1.0.0",
    icon: "Store",
    recommended: true,
    features: [
      "FA2 compliant",
      "On-chain royalties",
      "Instant buy listings",
      "Partial-fill offers",
      "Pull payments",
      "Per-owner blacklist",
      "Owner-scoped controls",
    ],
    entrypoints: {
      mint: "mint",
      transfer: "transfer",
      updateOperators: "update_operators",
      setPrice: "set_price",
      clearPrice: "clear_price",
      buy: "buy",
      makeOffer: "make_offer",
      acceptOffer: "accept_offer",
      rejectOffer: "reject_offer",
      cancelOffer: "cancel_offer",
      sweepExpiredOffer: "sweep_expired_offer",
      withdraw: "withdraw",
      blacklistAddress: "blacklist_address",
      unblacklistAddress: "unblacklist_address",
      setMaxBuyQty: "set_max_buy_qty",
      setMinOfferPercentOfList: "set_min_offer_percent_of_list",
    },
  },
  {
    id: "bowers-open-edition",
    name: "Bowers Open Edition",
    description: "Open-edition FA2 where anyone can mint editions at a set price. Includes built-in marketplace with listings, 7-day auto-expiring offers, pull payments, and per-owner blacklists.",
    version: "1.0.0",
    icon: "Infinity",
    features: [
      "FA2 compliant",
      "Open-edition minting",
      "On-chain royalties",
      "Instant buy listings",
      "Partial-fill offers",
      "7-day auto-expiry",
      "Pull payments",
      "Per-owner blacklist",
      "Mint controls",
    ],
    entrypoints: {
      mint: "mint_editions",
      transfer: "transfer",
      updateOperators: "update_operators",
      createToken: "create_token",
      mintEditions: "mint_editions",
      setMintPrice: "set_mint_price",
      setMintEnd: "set_mint_end",
      setMintPausedForever: "set_mint_paused_forever",
      setMintingPaused: "set_minting_paused",
      setPrice: "set_price",
      clearPrice: "clear_price",
      buy: "buy",
      makeOffer: "make_offer",
      acceptOffer: "accept_offer",
      cancelOffer: "cancel_offer",
      adminCancelExpiredOffer: "admin_cancel_expired_offer",
      withdraw: "withdraw",
      blacklistAddress: "blacklist_address",
      unblacklistAddress: "unblacklist_address",
      setMaxBuyQty: "set_max_buy_qty",
      setMinOfferPercentOfList: "set_min_offer_percent_of_list",
    },
  },
];
