/**
 * Reads the global-constants.json mapping (produced by register-global-constants.ts)
 * and rewrites each contract's TypeScript module so the code body is replaced
 * with a constant reference `{ prim: "constant", args: [{ string: "exprXXX" }] }`.
 *
 * The resulting slim modules keep parameter, storage, and view sections inline,
 * while the heavy code body is referenced via global constant hash.
 *
 * Usage:
 *   npx tsx scripts/apply-global-constants.ts [network]
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve } from "path";

const MICHELSON_DIR = resolve(__dirname, "../client/src/lib/tezos/michelson");
const CONSTANTS_FILE = resolve(MICHELSON_DIR, "global-constants.json");

function main() {
  const network = process.argv[2] || "ghostnet";

  if (!existsSync(CONSTANTS_FILE)) {
    console.error(`Missing ${CONSTANTS_FILE}. Run register-global-constants.ts first.`);
    process.exit(1);
  }

  const mapping = JSON.parse(readFileSync(CONSTANTS_FILE, "utf8"));
  const networkMap = mapping[network];

  if (!networkMap || Object.keys(networkMap).length === 0) {
    console.error(`No constants registered for network "${network}".`);
    process.exit(1);
  }

  for (const [contractId, entry] of Object.entries(networkMap) as [string, any][]) {
    const jsonPath = resolve(MICHELSON_DIR, `${contractId}.json`);
    const tsPath = resolve(MICHELSON_DIR, `${contractId}.ts`);

    if (!existsSync(jsonPath)) {
      console.log(`[${contractId}] JSON not found — skipping`);
      continue;
    }

    const contract: any[] = JSON.parse(readFileSync(jsonPath, "utf8"));
    const codeIdx = contract.findIndex((el: any) => el.prim === "code");
    if (codeIdx === -1) {
      console.log(`[${contractId}] No code section — skipping`);
      continue;
    }

    const slimContract = contract.map((el: any, i: number) => {
      if (i !== codeIdx) return el;
      return {
        prim: "code",
        args: [[{ prim: "constant", args: [{ string: entry.codeHash }] }]],
      };
    });

    const slimJson = JSON.stringify(slimContract);
    const slimKB = (slimJson.length / 1024).toFixed(1);

    const tsContent = `// Generated by scripts/apply-global-constants.ts — do not edit manually.\n// Uses global constant ${entry.codeHash} for the code body.\nexport const code: unknown[] = ${slimJson};\n`;

    writeFileSync(tsPath, tsContent);
    console.log(`[${contractId}] Wrote slim module: ${slimKB} KB (was ${(JSON.stringify(contract).length / 1024).toFixed(1)} KB)`);
  }

  console.log("\nDone. Rebuild the project to use slim contract modules.");
}

main();
